import * as React from "react";
import SubpageContainer, { SubpageContainerProps } from "../components/SubpageContainer";


/** Main component for the about page. */
export class About extends React.Component<SubpageContainerProps> {
  render() {
    return (
      <SubpageContainer overlay={this.props.overlay} onClickUnmountSubpageHandler={this.props.onClickUnmountSubpageHandler}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae nesciunt ipsam labore amet in, reprehenderit, molestiae eum ipsa inventore tempora, repudiandae iure odio neque. Soluta repellat eius amet incidunt asperiores.<br />Laborum in magni nisi, modi natus a voluptate alias consectetur minus ipsa molestias fuga inventore dignissimos tenetur aut similique rem veniam? Ullam, quidem quis provident adipisci ab ex inventore quod.<br />Pariatur eaque odio, aliquid, architecto eius consectetur molestias neque quam autem iste expedita reiciendis sed ea, tenetur animi repellendus! Nisi quae fuga numquam eius veritatis, odit laudantium consectetur inventore distinctio.<br />Placeat inventore dignissimos commodi ipsum accusantium hic optio ex aspernatur similique obcaecati eligendi, possimus in consequatur at voluptas. Tempora nisi dignissimos voluptas? Quisquam facere amet culpa obcaecati placeat similique dicta.<br />Iusto ducimus temporibus laboriosam optio, neque, deserunt hic fuga ipsum tenetur praesentium, a ipsam repudiandae natus deleniti sed quasi mollitia commodi id. Cupiditate voluptates corrupti officiis sunt debitis, quam libero.<br />Commodi laborum fuga debitis, sit itaque libero totam? Accusamus quo fuga pariatur praesentium! Molestiae accusantium, distinctio atque neque eligendi ipsum molestias repellendus, esse quis quia fuga reiciendis sapiente? Vero, ad!<br />Consequuntur cum vel doloribus tempore nam exercitationem illo cumque distinctio consequatur fugit, nulla rerum neque voluptatibus similique asperiores repudiandae commodi minus numquam magni quibusdam! Labore ullam molestiae aliquid itaque consectetur?<br />Nihil, rerum voluptatem? Sed, rerum voluptas quaerat harum, voluptatibus exercitationem eum maxime ad dolor maiores sequi placeat delectus, ut atque ipsam? Deserunt, sequi. Sit aliquid modi iusto eius quaerat quos.<br />Nesciunt vitae, placeat minus repudiandae cumque tempore molestiae veniam quaerat odit accusamus deleniti saepe! Temporibus, ipsam a sed odit natus vitae veniam? Animi, explicabo officiis! Amet eligendi odio sed dolores.<br />Cumque omnis expedita atque provident tempore earum sequi ab, ullam maxime esse, iste, eligendi et quidem sunt eius quisquam officiis inventore cupiditate. Quae sapiente autem suscipit doloribus neque eaque maxime?<br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae nesciunt ipsam labore amet in, reprehenderit, molestiae eum ipsa inventore tempora, repudiandae iure odio neque. Soluta repellat eius amet incidunt asperiores.<br />Laborum in magni nisi, modi natus a voluptate alias consectetur minus ipsa molestias fuga inventore dignissimos tenetur aut similique rem veniam? Ullam, quidem quis provident adipisci ab ex inventore quod.<br />Pariatur eaque odio, aliquid, architecto eius consectetur molestias neque quam autem iste expedita reiciendis sed ea, tenetur animi repellendus! Nisi quae fuga numquam eius veritatis, odit laudantium consectetur inventore distinctio.<br />Placeat inventore dignissimos commodi ipsum accusantium hic optio ex aspernatur similique obcaecati eligendi, possimus in consequatur at voluptas. Tempora nisi dignissimos voluptas? Quisquam facere amet culpa obcaecati placeat similique dicta.<br />Iusto ducimus temporibus laboriosam optio, neque, deserunt hic fuga ipsum tenetur praesentium, a ipsam repudiandae natus deleniti sed quasi mollitia commodi id. Cupiditate voluptates corrupti officiis sunt debitis, quam libero.<br />Commodi laborum fuga debitis, sit itaque libero totam? Accusamus quo fuga pariatur praesentium! Molestiae accusantium, distinctio atque neque eligendi ipsum molestias repellendus, esse quis quia fuga reiciendis sapiente? Vero, ad!<br />Consequuntur cum vel doloribus tempore nam exercitationem illo cumque distinctio consequatur fugit, nulla rerum neque voluptatibus similique asperiores repudiandae commodi minus numquam magni quibusdam! Labore ullam molestiae aliquid itaque consectetur?<br />Nihil, rerum voluptatem? Sed, rerum voluptas quaerat harum, voluptatibus exercitationem eum maxime ad dolor maiores sequi placeat delectus, ut atque ipsam? Deserunt, sequi. Sit aliquid modi iusto eius quaerat quos.<br />Nesciunt vitae, placeat minus repudiandae cumque tempore molestiae veniam quaerat odit accusamus deleniti saepe! Temporibus, ipsam a sed odit natus vitae veniam? Animi, explicabo officiis! Amet eligendi odio sed dolores.<br />Cumque omnis expedita atque provident tempore earum sequi ab, ullam maxime esse, iste, eligendi et quidem sunt eius quisquam officiis inventore cupiditate. Quae sapiente autem suscipit doloribus neque eaque maxime?<br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae nesciunt ipsam labore amet in, reprehenderit, molestiae eum ipsa inventore tempora, repudiandae iure odio neque. Soluta repellat eius amet incidunt asperiores.<br />Laborum in magni nisi, modi natus a voluptate alias consectetur minus ipsa molestias fuga inventore dignissimos tenetur aut similique rem veniam? Ullam, quidem quis provident adipisci ab ex inventore quod.<br />Pariatur eaque odio, aliquid, architecto eius consectetur molestias neque quam autem iste expedita reiciendis sed ea, tenetur animi repellendus! Nisi quae fuga numquam eius veritatis, odit laudantium consectetur inventore distinctio.<br />Placeat inventore dignissimos commodi ipsum accusantium hic optio ex aspernatur similique obcaecati eligendi, possimus in consequatur at voluptas. Tempora nisi dignissimos voluptas? Quisquam facere amet culpa obcaecati placeat similique dicta.<br />Iusto ducimus temporibus laboriosam optio, neque, deserunt hic fuga ipsum tenetur praesentium, a ipsam repudiandae natus deleniti sed quasi mollitia commodi id. Cupiditate voluptates corrupti officiis sunt debitis, quam libero.<br />Commodi laborum fuga debitis, sit itaque libero totam? Accusamus quo fuga pariatur praesentium! Molestiae accusantium, distinctio atque neque eligendi ipsum molestias repellendus, esse quis quia fuga reiciendis sapiente? Vero, ad!<br />Consequuntur cum vel doloribus tempore nam exercitationem illo cumque distinctio consequatur fugit, nulla rerum neque voluptatibus similique asperiores repudiandae commodi minus numquam magni quibusdam! Labore ullam molestiae aliquid itaque consectetur?<br />Nihil, rerum voluptatem? Sed, rerum voluptas quaerat harum, voluptatibus exercitationem eum maxime ad dolor maiores sequi placeat delectus, ut atque ipsam? Deserunt, sequi. Sit aliquid modi iusto eius quaerat quos.<br />Nesciunt vitae, placeat minus repudiandae cumque tempore molestiae veniam quaerat odit accusamus deleniti saepe! Temporibus, ipsam a sed odit natus vitae veniam? Animi, explicabo officiis! Amet eligendi odio sed dolores.<br />Cumque omnis expedita atque provident tempore earum sequi ab, ullam maxime esse, iste, eligendi et quidem sunt eius quisquam officiis inventore cupiditate. Quae sapiente autem suscipit doloribus neque eaque maxime?<br />
      </SubpageContainer>
    )
  }
}

export default About;
